name: CI

on:
  push:
  pull_request:
    types: [opened, reopened]

defaults:
  run:
    shell: bash

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          git clone --depth 1 --single-branch --branch 1.2.0rc2 https://github.com/python-poetry/poetry.git
          pushd poetry
          python install-poetry.py --version 1.2.0rc2
          popd
          rm -r poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH

          if [ "${{ runner.os }}" == "macOS" ]; then
            # is needed for macos to make poetry available
            export PATH="/Users/runner/.local/bin:$PATH"
          fi
          poetry env use ${{ matrix.python-version }}
          poetry install --verbose

      - name: Lint
        run: |
          bash ./lint.sh modapp_cicdtools

      - name: Run unit tests
        if: ${{ !cancelled() }}
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry run python -m pytest tests/

      - name: Build
        if: ${{ !cancelled() }}
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry run python -m nuitka modapp_cicdtools/cli.py

      - uses: actions/upload-artifact@v3
        with:
          name: cicdtools ${{ matrix.os }}
          path: ${{ github.workspace }}/cli.bin
