name: CI

on:
  push:
  pull_request:
    types: [opened, reopened]

defaults:
  run:
    shell: bash

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry==1.2.0rc2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install --verbose

      - name: Lint
        run: |
          bash ./lint.sh modapp_cicdtools

      - name: Run unit tests
        if: ${{ !cancelled() }}
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry run python -m pytest tests/

      - name: Build
        if: ${{ !cancelled() }}
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry run python -m nuitka modapp_cicdtools/cli.py

      - uses: actions/upload-artifact@v3
        with:
          name: cicdtools ${{ matrix.os }}
          path: ${{ github.workspace }}/cli.bin
